services:
  db:
    context: ./mysql
    image: jumice93/calculadora:v1
    container_name: contenedordb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personas
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
     - "3306:3306"
     
  php:
    context: ./php
    image: jumice93/calculadora:v1
    container_name: contenedorMiApp
    ports:
      - "8080:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedorPhpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
     - db
